name: warehouse_transform
version: "1.0.0"
config-version: 2

profile: warehouse

model-paths: [models]
test-paths: [tests]
macro-paths: [macros]
docs-paths: [docs]
target-path: target
clean-targets: [target, dbt_packages]

models:
  warehouse_transform:
    staging:
      +schema: staging
      +materialized: view
      +tags: [domain:orders, layer:staging, owner:dbt]

    marts:
      +schema: marts
      +materialized: view
      +tags: [domain:orders, layer:marts, owner:dbt]
