apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      derivedFields:
        - name: TraceID
          matcherType: label
          matcherRegex: ^trace[_]?id$
          datasourceUid: tempo
          url: '$${__value.raw}'
          urlDisplayLabel: Tempo trace
