#!/usr/bin/env bash
set -euo pipefail

: "${METADATA_DB_NAME:?METADATA_DB_NAME is required}"
: "${METADATA_DB_USER:?METADATA_DB_USER is required}"
: "${METADATA_DB_PASSWORD:?METADATA_DB_PASSWORD is required}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname postgres <<SQL
CREATE ROLE "$METADATA_DB_USER" LOGIN PASSWORD '$METADATA_DB_PASSWORD'
  NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT;
CREATE DATABASE "$METADATA_DB_NAME" OWNER "$METADATA_DB_USER";
\connect "$METADATA_DB_NAME"
ALTER SCHEMA public OWNER TO "$METADATA_DB_USER";
GRANT USAGE, CREATE ON SCHEMA public TO "$METADATA_DB_USER";
SQL
