import os

SECRET_KEY = os.environ["SUPERSET_SECRET_KEY"]

# Local development only.
MCP_AUTH_ENABLED = False
MCP_DEV_USERNAME = "admin"

MCP_SERVICE_HOST = "0.0.0.0"
MCP_SERVICE_PORT = 5008

# Browser-facing URLs generated by Superset MCP.
SUPERSET_WEBSERVER_PROTOCOL = "http"
SUPERSET_WEBSERVER_ADDRESS = "localhost"
SUPERSET_WEBSERVER_PORT = 18088
