import os

SECRET_KEY = os.environ["SUPERSET_SECRET_KEY"]

# Local-development MCP configuration.
# Requests are executed with the permissions of this existing Superset user.
MCP_AUTH_ENABLED = False
MCP_DEV_USERNAME = "admin"

MCP_SERVICE_HOST = "0.0.0.0"
MCP_SERVICE_PORT = 5008

# Links generated by MCP tools should point to the browser-accessible Superset.
MCP_SERVICE_URL = "http://localhost:15008"